// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: v1/cron.proto

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// CronServiceClient is the client API for CronService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CronServiceClient interface {
}

type cronServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCronServiceClient(cc grpc.ClientConnInterface) CronServiceClient {
	return &cronServiceClient{cc}
}

// CronServiceServer is the server API for CronService service.
// All implementations must embed UnimplementedCronServiceServer
// for forward compatibility
type CronServiceServer interface {
	mustEmbedUnimplementedCronServiceServer()
}

// UnimplementedCronServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCronServiceServer struct {
}

func (UnimplementedCronServiceServer) mustEmbedUnimplementedCronServiceServer() {}

// UnsafeCronServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CronServiceServer will
// result in compilation errors.
type UnsafeCronServiceServer interface {
	mustEmbedUnimplementedCronServiceServer()
}

func RegisterCronServiceServer(s grpc.ServiceRegistrar, srv CronServiceServer) {
	s.RegisterService(&CronService_ServiceDesc, srv)
}

// CronService_ServiceDesc is the grpc.ServiceDesc for CronService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CronService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.cron.CronService",
	HandlerType: (*CronServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "v1/cron.proto",
}
