// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/daemon.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on HealthInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HealthInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HealthInfoMultiError, or
// nil if none found.
func (m *HealthInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CpuCount

	// no validation rules for MemorySize

	// no validation rules for CpuPercent

	if len(errors) > 0 {
		return HealthInfoMultiError(errors)
	}

	return nil
}

// HealthInfoMultiError is an error wrapping multiple validation errors
// returned by HealthInfo.ValidateAll() if the designated constraints aren't met.
type HealthInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthInfoMultiError) AllErrors() []error { return m }

// HealthInfoValidationError is the validation error returned by
// HealthInfo.Validate if the designated constraints aren't met.
type HealthInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthInfoValidationError) ErrorName() string { return "HealthInfoValidationError" }

// Error satisfies the builtin error interface
func (e HealthInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthInfoValidationError{}
