// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/dst.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on KleiId with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *KleiId) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KleiId with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in KleiIdMultiError, or nil if none found.
func (m *KleiId) ValidateAll() error {
	return m.validate(true)
}

func (m *KleiId) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return KleiIdMultiError(errors)
	}

	return nil
}

// KleiIdMultiError is an error wrapping multiple validation errors returned by
// KleiId.ValidateAll() if the designated constraints aren't met.
type KleiIdMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KleiIdMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KleiIdMultiError) AllErrors() []error { return m }

// KleiIdValidationError is the validation error returned by KleiId.Validate if
// the designated constraints aren't met.
type KleiIdValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KleiIdValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KleiIdValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KleiIdValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KleiIdValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KleiIdValidationError) ErrorName() string { return "KleiIdValidationError" }

// Error satisfies the builtin error interface
func (e KleiIdValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKleiId.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KleiIdValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KleiIdValidationError{}

// Validate checks the field values on InstanceId with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *InstanceId) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InstanceId with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in InstanceIdMultiError, or
// nil if none found.
func (m *InstanceId) ValidateAll() error {
	return m.validate(true)
}

func (m *InstanceId) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InstanceId

	if len(errors) > 0 {
		return InstanceIdMultiError(errors)
	}

	return nil
}

// InstanceIdMultiError is an error wrapping multiple validation errors
// returned by InstanceId.ValidateAll() if the designated constraints aren't met.
type InstanceIdMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InstanceIdMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InstanceIdMultiError) AllErrors() []error { return m }

// InstanceIdValidationError is the validation error returned by
// InstanceId.Validate if the designated constraints aren't met.
type InstanceIdValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InstanceIdValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InstanceIdValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InstanceIdValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InstanceIdValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InstanceIdValidationError) ErrorName() string { return "InstanceIdValidationError" }

// Error satisfies the builtin error interface
func (e InstanceIdValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInstanceId.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InstanceIdValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InstanceIdValidationError{}
