// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: v1/mod.proto

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// ModServiceClient is the client API for ModService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModServiceClient interface {
}

type modServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModServiceClient(cc grpc.ClientConnInterface) ModServiceClient {
	return &modServiceClient{cc}
}

// ModServiceServer is the server API for ModService service.
// All implementations must embed UnimplementedModServiceServer
// for forward compatibility
type ModServiceServer interface {
	mustEmbedUnimplementedModServiceServer()
}

// UnimplementedModServiceServer must be embedded to have forward compatible implementations.
type UnimplementedModServiceServer struct {
}

func (UnimplementedModServiceServer) mustEmbedUnimplementedModServiceServer() {}

// UnsafeModServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModServiceServer will
// result in compilation errors.
type UnsafeModServiceServer interface {
	mustEmbedUnimplementedModServiceServer()
}

func RegisterModServiceServer(s grpc.ServiceRegistrar, srv ModServiceServer) {
	s.RegisterService(&ModService_ServiceDesc, srv)
}

// ModService_ServiceDesc is the grpc.ServiceDesc for ModService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.mod.ModService",
	HandlerType: (*ModServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "v1/mod.proto",
}
