// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: v1/player.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Player operation
type Operation int32

const (
	// kill a specific online player
	Operation_Kill Operation = 0
	// kick a specific online player from the server
	Operation_Kick Operation = 1
	// make the specific online player change his role
	Operation_ReRole Operation = 2
	// / make the specific dead player reborn
	Operation_ReBorn Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "Kill",
		1: "Kick",
		2: "ReRole",
		3: "ReBorn",
	}
	Operation_value = map[string]int32{
		"Kill":   0,
		"Kick":   1,
		"ReRole": 2,
		"ReBorn": 3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_player_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_v1_player_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_v1_player_proto_rawDescGZIP(), []int{0}
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// steam user id
	SteamId uint64 `protobuf:"varint,1,opt,name=steamId,proto3" json:"steamId,omitempty"`
	// klei user id
	Kid string `protobuf:"bytes,2,opt,name=kid,proto3" json:"kid,omitempty"`
	// dst player name, same as steam user name normally
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// dst role the player played, like wilson, wendy
	Role string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// if is server admin
	Admin bool `protobuf:"varint,5,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_v1_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_v1_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetSteamId() uint64 {
	if x != nil {
		return x.SteamId
	}
	return 0
}

func (x *Player) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Player) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

// server player information
type PlayerStatisticInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total              int64     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	TotalOnline        int64     `protobuf:"varint,2,opt,name=totalOnline,proto3" json:"totalOnline,omitempty"`
	MasterOnline       int64     `protobuf:"varint,3,opt,name=masterOnline,proto3" json:"masterOnline,omitempty"`
	CaveOnline         int64     `protobuf:"varint,4,opt,name=caveOnline,proto3" json:"caveOnline,omitempty"`
	TotalPlayer        []*Player `protobuf:"bytes,5,rep,name=totalPlayer,proto3" json:"totalPlayer,omitempty"`
	MasterOnlinePlayer []*Player `protobuf:"bytes,6,rep,name=masterOnlinePlayer,proto3" json:"masterOnlinePlayer,omitempty"`
	CaveOnlinePlayer   []*Player `protobuf:"bytes,7,rep,name=caveOnlinePlayer,proto3" json:"caveOnlinePlayer,omitempty"`
}

func (x *PlayerStatisticInfo) Reset() {
	*x = PlayerStatisticInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_player_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerStatisticInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatisticInfo) ProtoMessage() {}

func (x *PlayerStatisticInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_player_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatisticInfo.ProtoReflect.Descriptor instead.
func (*PlayerStatisticInfo) Descriptor() ([]byte, []int) {
	return file_v1_player_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerStatisticInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PlayerStatisticInfo) GetTotalOnline() int64 {
	if x != nil {
		return x.TotalOnline
	}
	return 0
}

func (x *PlayerStatisticInfo) GetMasterOnline() int64 {
	if x != nil {
		return x.MasterOnline
	}
	return 0
}

func (x *PlayerStatisticInfo) GetCaveOnline() int64 {
	if x != nil {
		return x.CaveOnline
	}
	return 0
}

func (x *PlayerStatisticInfo) GetTotalPlayer() []*Player {
	if x != nil {
		return x.TotalPlayer
	}
	return nil
}

func (x *PlayerStatisticInfo) GetMasterOnlinePlayer() []*Player {
	if x != nil {
		return x.MasterOnlinePlayer
	}
	return nil
}

func (x *PlayerStatisticInfo) GetCaveOnlinePlayer() []*Player {
	if x != nil {
		return x.CaveOnlinePlayer
	}
	return nil
}

// server shard log player message
type LogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	// message event, eg. say, whisper, announcement
	Event string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Msg   string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_player_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_player_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_v1_player_proto_rawDescGZIP(), []int{2}
}

func (x *LogMessage) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *LogMessage) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *LogMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PlayerChatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*LogMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *PlayerChatInfo) Reset() {
	*x = PlayerChatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_player_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerChatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerChatInfo) ProtoMessage() {}

func (x *PlayerChatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_player_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerChatInfo.ProtoReflect.Descriptor instead.
func (*PlayerChatInfo) Descriptor() ([]byte, []int) {
	return file_v1_player_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerChatInfo) GetMessages() []*LogMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_v1_player_proto protoreflect.FileDescriptor

var file_v1_player_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x1a, 0x0c, 0x76, 0x31,
	0x2f, 0x64, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x06, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0xc8,
	0x02, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x76, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x61, 0x76, 0x65, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x12, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x12, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x10, 0x63, 0x61,
	0x76, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x10, 0x63, 0x61, 0x76, 0x65, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x48, 0x0a, 0x0a, 0x4c, 0x6f, 0x67,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x43, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2a, 0x37, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x69, 0x6c, 0x6c, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x4b, 0x69, 0x63, 0x6b, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x65, 0x52,
	0x6f, 0x6c, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x65, 0x42, 0x6f, 0x72, 0x6e, 0x10,
	0x03, 0x32, 0x94, 0x01, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x64, 0x73, 0x74, 0x2e, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x1a, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x12, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x64,
	0x73, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x1a, 0x19, 0x2e,
	0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x0b, 0x5a, 0x09, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_player_proto_rawDescOnce sync.Once
	file_v1_player_proto_rawDescData = file_v1_player_proto_rawDesc
)

func file_v1_player_proto_rawDescGZIP() []byte {
	file_v1_player_proto_rawDescOnce.Do(func() {
		file_v1_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_player_proto_rawDescData)
	})
	return file_v1_player_proto_rawDescData
}

var file_v1_player_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_player_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_player_proto_goTypes = []interface{}{
	(Operation)(0),              // 0: v1.player.Operation
	(*Player)(nil),              // 1: v1.player.Player
	(*PlayerStatisticInfo)(nil), // 2: v1.player.PlayerStatisticInfo
	(*LogMessage)(nil),          // 3: v1.player.LogMessage
	(*PlayerChatInfo)(nil),      // 4: v1.player.PlayerChatInfo
	(*InstanceId)(nil),          // 5: v1.dst.InstanceId
}
var file_v1_player_proto_depIdxs = []int32{
	1, // 0: v1.player.PlayerStatisticInfo.totalPlayer:type_name -> v1.player.Player
	1, // 1: v1.player.PlayerStatisticInfo.masterOnlinePlayer:type_name -> v1.player.Player
	1, // 2: v1.player.PlayerStatisticInfo.caveOnlinePlayer:type_name -> v1.player.Player
	3, // 3: v1.player.PlayerChatInfo.messages:type_name -> v1.player.LogMessage
	5, // 4: v1.player.PlayerService.GetPlayerInfo:input_type -> v1.dst.InstanceId
	5, // 5: v1.player.PlayerService.GetPlayerChat:input_type -> v1.dst.InstanceId
	2, // 6: v1.player.PlayerService.GetPlayerInfo:output_type -> v1.player.PlayerStatisticInfo
	4, // 7: v1.player.PlayerService.GetPlayerChat:output_type -> v1.player.PlayerChatInfo
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_player_proto_init() }
func file_v1_player_proto_init() {
	if File_v1_player_proto != nil {
		return
	}
	file_v1_dst_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_player_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerStatisticInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_player_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_player_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerChatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_player_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_player_proto_goTypes,
		DependencyIndexes: file_v1_player_proto_depIdxs,
		EnumInfos:         file_v1_player_proto_enumTypes,
		MessageInfos:      file_v1_player_proto_msgTypes,
	}.Build()
	File_v1_player_proto = out.File
	file_v1_player_proto_rawDesc = nil
	file_v1_player_proto_goTypes = nil
	file_v1_player_proto_depIdxs = nil
}
