// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"github.com/dstgo/wilson/app/conf"
	"github.com/dstgo/wilson/app/core/auth"
	"github.com/dstgo/wilson/app/data"
	auth2 "github.com/dstgo/wilson/app/handler/auth"
	email2 "github.com/dstgo/wilson/app/handler/email"
	"github.com/dstgo/wilson/app/handler/system"
	"github.com/dstgo/wilson/app/handler/user"
	"github.com/dstgo/wilson/pkg/route"
	"github.com/jordan-wright/email"
)

// Injectors from wire.go:

//go:generate wire gen
func SetupHandler(appConf *conf.AppConf, api *route.Router, datasource *data.DataSource, issue auth.Issuer, pool *email.Pool) Router {
	infoData := user.NewInfoData(datasource)
	authLogic := auth2.NewAuthLogic(issue, infoData, datasource)
	authHandler := auth2.NewAuthHandler(authLogic)
	roleLogic := auth2.NewRoleLogic()
	roleHandler := auth2.NewRoleHandler(roleLogic)
	handler := auth2.Handler{
		Auth: authHandler,
		Role: roleHandler,
	}
	handlerRouter := auth2.SetupRouter(api, handler)
	emailLogic := email2.NewEmailLogic(appConf, pool)
	emailHandler := email2.NewEmailHandler(appConf, emailLogic, datasource)
	handler2 := email2.Handler{
		Email: emailHandler,
	}
	emailHandlerRouter := email2.SetupRouter(api, handler2)
	pingLogic := system.NewPingLogic(appConf)
	pingHandler := system.NewPingHandler(pingLogic)
	systemHandler := system.Handler{
		Ping: pingHandler,
	}
	systemHandlerRouter := system.SetupRouter(api, systemHandler)
	infoLogic := user.NewInfoLogic(infoData)
	infoHandler := user.NewInfoHandler(infoLogic)
	userHandler := user.Handler{
		Info: infoHandler,
	}
	userHandlerRouter := user.SetupRouter(api, userHandler)
	router := Router{
		Auth:   handlerRouter,
		Email:  emailHandlerRouter,
		System: systemHandlerRouter,
		User:   userHandlerRouter,
	}
	return router
}
