// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"github.com/dstgo/wilson/internal/conf"
	"github.com/dstgo/wilson/internal/data"
	"github.com/dstgo/wilson/internal/handler/email"
	"github.com/dstgo/wilson/internal/handler/system"
	"github.com/dstgo/wilson/internal/handler/user"
	"github.com/dstgo/wilson/internal/core/authen"
	"github.com/dstgo/wilson/pkg/route"
)

// Injectors from wire.go:

//go:generate wire gen
func setupHandlerRouter(appConf *conf.AppConf, api *route.Router, datasource *data.DataSource) (Router, func(), error) {
	sender, cleanup, err := email.NewSender(appConf)
	if err != nil {
		return Router{}, nil, err
	}
	codeCache := email.NewEmailCodeCache(datasource)
	emailHandler := email.NewEmailHandler(appConf, sender, codeCache)
	handler := email.Handler{
		Email: emailHandler,
	}
	handlerRouter := email.SetupRouter(api, handler)
	pingLogic := system.NewPingLogic(appConf)
	pingHandler := system.NewPingHandler(pingLogic)
	infoData := user.NewInfoData(datasource)
	redisTokenCache := authen.NewTokenRedisCache(datasource)
	authenticator := system.NewAuthenticator(appConf, infoData, codeCache, redisTokenCache)
	authHandler := system.NewAuthHandler(authenticator)
	systemHandler := system.Handler{
		Ping: pingHandler,
		Auth: authHandler,
	}
	systemHandlerRouter := system.SetupRouter(api, systemHandler)
	userInfo := user.NewUserInfo(infoData)
	infoHandler := user.NewInfoHandler(userInfo)
	userHandler := user.Handler{
		Info: infoHandler,
	}
	userHandlerRouter := user.SetupRouter(api, userHandler)
	router := Router{
		Email:  handlerRouter,
		System: systemHandlerRouter,
		User:   userHandlerRouter,
	}
	return router, func() {
		cleanup()
	}, nil
}
