// Package swagger Code generated by swaggo/swag at 2023-10-14 16:54:23.7263181 +0800 CST m=+3.359557601. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplateopenapi = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/open/user/info": {
            "get": {
                "description": "get user simple info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    ""
                ],
                "summary": "path params example",
                "parameters": [
                    {
                        "type": "string",
                        "description": "comment",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "request.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.RegisterRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoopenapi holds exported Swagger Info so clients can modify it
var SwaggerInfoopenapi = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "",
	BasePath:         "/open/doc/",
	Schemes:          []string{},
	Title:            "Wilson App Internal API Documentation",
	Description:      "Wilson api documentation",
	InfoInstanceName: "openapi",
	SwaggerTemplate:  docTemplateopenapi,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoopenapi.InstanceName(), SwaggerInfoopenapi)
}
