basePath: /api/v1
definitions:
  request.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  resp.Response:
    properties:
      code:
        description: custom Code
        type: integer
      data:
        description: response Data
      error:
        description: response Error
        type: string
      msg:
        description: response mgs
        type: string
    type: object
info:
  contact: {}
  description: Wilson api documentation
  title: Wilson App Internal API Documentation
  version: v1.0.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: if login success, return jwt token
      parameters:
      - description: comment
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses: {}
      summary: user login api
      tags:
      - system/auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: user register api
      parameters:
      - description: comment
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: comment
          schema:
            type: string
        "400":
          description: comment
          schema:
            type: string
      summary: user register api
      tags:
      - system/auth
  /ping:
    get:
      consumes:
      - application/json
      description: to test app api if is ok
      parameters:
      - description: ping name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/resp.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: bad parameter
          schema:
            allOf:
            - $ref: '#/definitions/resp.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: app test ping api
      tags:
      - system
swagger: "2.0"
