// Code generated by swaggo/swag at 2023-08-22 12:41:35.1848185 +0800 CST m=+4.179338101. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplateopenapi = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfoopenapi holds exported Swagger Info so clients can modify it
var SwaggerInfoopenapi = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "",
	BasePath:         "/openapi/v1/",
	Schemes:          []string{},
	Title:            "Wilson App Open API Documentation",
	Description:      "Wilson api documentation",
	InfoInstanceName: "openapi",
	SwaggerTemplate:  docTemplateopenapi,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoopenapi.InstanceName(), SwaggerInfoopenapi)
}
