// Package docs Code generated by swaggo/swag at 2023-10-26 22:08:53.1784516 +0800 CST m=+3.372946701. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplateopenapi = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "dstgo",
            "url": "https://github.com/dstgo"
        },
        "license": {
            "name": "MIT LICENSE",
            "url": "https://mit-license.org/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api": {
            "get": {
                "description": "get user info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "UserInfo",
                "parameters": [
                    {
                        "type": "string",
                        "name": "uuid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.Info"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "role.RoleInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "role code, must be alpha numeric",
                    "type": "string",
                    "example": "ADMIN"
                },
                "id": {
                    "description": "role id",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "role name",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "types.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 2000
                },
                "data": {},
                "err": {
                    "type": "string"
                },
                "msg": {
                    "type": "string",
                    "example": "operation success"
                }
            }
        },
        "user.Info": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "integer",
                    "example": 947416200
                },
                "email": {
                    "type": "string",
                    "example": "jacklove@lol.com"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role.RoleInfo"
                    }
                },
                "username": {
                    "type": "string",
                    "example": "jack"
                },
                "uuid": {
                    "type": "string",
                    "example": "55BBA4ED-18D3-790F-EABF-A5330E527586"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "key",
            "in": "query"
        }
    }
}`

// SwaggerInfoopenapi holds exported Swagger Info so clients can modify it
var SwaggerInfoopenapi = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "",
	BasePath:         "/open/v1",
	Schemes:          []string{},
	Title:            "Wilson App Open API Documentation",
	Description:      "Wilson open api documentation, to access these open api, you need to add apikey in query param named \"key\"",
	InfoInstanceName: "openapi",
	SwaggerTemplate:  docTemplateopenapi,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoopenapi.InstanceName(), SwaggerInfoopenapi)
}
