// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package appapi

import (
	systemApi2 "github.com/dstgo/wilson/app/api/appapi/system"
	userApi2 "github.com/dstgo/wilson/app/api/appapi/user"
	"github.com/dstgo/wilson/app/conf"
	"github.com/dstgo/wilson/app/dao/userDao"
	"github.com/dstgo/wilson/app/data"
	"github.com/dstgo/wilson/app/logic/systemLogic"
	"github.com/dstgo/wilson/app/logic/userLogic"
	"github.com/dstgo/wilson/pkg/route"
)

// Injectors from api_wire.go:

//go:generate wire gen -output_file_prefix api_
func NewApiRouter(appConf *conf.AppConf, rootRouter *route.Router, datasource *data.DataSource) ApiRouter {
	pingLogic := systemLogic.NewPingLogic(appConf)
	pingApi := systemApi2.NewPingApi(appConf, pingLogic)
	router := systemApi2.NewSystemRouter(rootRouter, pingApi)
	userInfoDao := userDao.NewUserInfoDao(datasource)
	userInfoLogic := userLogic.NewUserLogic(userInfoDao)
	userInfoApi := userApi2.NewUserInfoApi(userInfoLogic)
	userApiRouter := userApi2.NewUserRouter(rootRouter, userInfoApi)
	apiRouter := ApiRouter{
		SystemApi: router,
		UserApi:   userApiRouter,
	}
	return apiRouter
}
