// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package appapi

import (
	"github.com/dstgo/wilson/app/api/appapi/system"
	"github.com/dstgo/wilson/app/api/appapi/user"
	"github.com/dstgo/wilson/app/conf"
	"github.com/dstgo/wilson/app/core/auth"
	"github.com/dstgo/wilson/app/dao/userDao"
	"github.com/dstgo/wilson/app/data"
	"github.com/dstgo/wilson/app/logic/systemLogic"
	"github.com/dstgo/wilson/app/logic/userLogic"
	"github.com/dstgo/wilson/pkg/route"
)

// Injectors from wire.go:

//go:generate wire gen
func NewApiRouter(appConf *conf.AppConf, rootRouter *route.Router, datasource *data.DataSource, issue auth.Issuer) ApiRouter {
	pingLogic := systemLogic.NewPingLogic(appConf)
	pingApi := system.NewPingApi(appConf, pingLogic)
	userInfoDao := userDao.NewUserInfoDao(datasource)
	authLogic := systemLogic.NewAuthLogic(issue, userInfoDao)
	authApi := system.NewAuthApi(authLogic)
	router := system.NewSystemRouter(rootRouter, pingApi, authApi)
	userInfoLogic := userLogic.NewUserLogic(userInfoDao)
	userInfoApi := user.NewUserInfoApi(userInfoLogic)
	userRouter := user.NewUserRouter(rootRouter, userInfoApi)
	apiRouter := ApiRouter{
		SystemApi: router,
		UserApi:   userRouter,
	}
	return apiRouter
}
