SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO `department` (`id`, `parent_id`, `keyword`, `name`, `description`, `created_at`, `updated_at`) VALUES (1, 0, 'dstgo', 'dstgo', '开源饥荒面板开发团队', UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (1, 0, '饥荒管理后台', 'R', 'SystemPlatform', 'apps', null, null, '/admin', null, 'Layout', null, 2, 0, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (2, 1, '首页', 'M', 'Dashboard', 'dashboard', null, null, '/admin/dashboard', null, '/admin/dashboard/index', null, 0, 0, 1, 1, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (3, 1, '管理中心', 'M', 'SystemPlatformManager', 'apps', null, null, '/admin/manager', null, null, null, 0, 0, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (4, 3, '基础接口', 'G', 'ManagerBaseApi', 'apps', null, null, null, null, null, null, 0, 1, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (5, 4, '获取用户可见部门树', 'BA', null, null, '/manager/api/v1/departments', 'GET', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (6, 4, '获取用户可见角色树', 'BA', null, null, '/manager/api/v1/roles', 'GET', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (7, 4, '获取个人用户信息', 'BA', null, null, '/manager/api/v1/user/current', 'GET', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (8, 4, '更新个人用户信息', 'BA', null, null, '/manager/api/v1/user/current/info', 'PUT', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (9, 4, '更新个人用户密码', 'BA', null, null, '/manager/api/v1/user/current/password', 'PUT', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (10, 4, '保存个人用户设置', 'BA', null, null, '/manager/api/v1/user/current/setting', 'PUT', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (11, 4, '发送用户验证吗', 'BA', null, null, '/manager/api/v1/user/current/captcha', 'POST', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (12, 4, '获取用户当前角色菜单', 'BA', null, null, '/manager/api/v1/menus/by/cur_role', 'GET', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (13, 4, '退出登录', 'BA', null, null, '/manager/api/v1/user/logout', 'POST', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (14, 4, '刷新token', 'BA', null, null, '/manager/api/v1/user/token/refresh', 'POST', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (15, 4, '用户登录', 'BA', null, null, '/manager/api/v1/user/login', 'POST', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (16, 4, '获取登录验证码', 'BA', null, null, '/manager/api/v1/user/login/captcha', 'POST', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (17, 4, '获取系统基础设置', 'BA', null, null, '/manager/api/v1/system/setting', 'GET', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (18, 4, '接口鉴权', 'BA', null, null, '/manager/api/v1/auth', 'POST', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (19, 4, '切换用户角色', 'BA', null, null, '/manager/api/v1/user/current/role', 'POST', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (20, 4, '分块上传文件', 'BA', null, null, '/resource/api/v1/upload', 'POST', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (21, 4, '预上传文件', 'BA', null, null, '/resource/api/v1/prepare_upload', 'POST', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (22, 4, '获取字段类型', 'BA', null, null, '/usercenter/api/v1/field/types', 'GET', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (23, 4, '查询资源权限', 'BA', null, null, '/manager/api/v1/resource', 'GET', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (24, 4, '获取渠道类型', 'BA', null, null, '/usercenter/api/v1/channel/types', 'GET', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (25, 3, '字典管理', 'M', 'ManagerDictionary', 'storage', null, null, '/admin/manager/dictionary', null, '/admin/manager/dictionary/index', null, 0, null, 1, null, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (26, 25, '查询字典', 'A', null, null, '/manager/api/v1/dictionaries', 'GET', null, 'manager:dictionary:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (27, 25, '新增字典', 'A', null, null, '/manager/api/v1/dictionary', 'POST', null, 'manager:dictionary:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (28, 25, '修改字典', 'A', null, null, '/manager/api/v1/dictionary', 'PUT', null, 'manager:dictionary:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (29, 25, '删除字典', 'A', null, null, '/manager/api/v1/dictionary', 'DELETE', null, 'manager:dictionary:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (30, 25, '获取字典值', 'A', null, null, '/manager/api/v1/dictionary_values', 'GET', null, 'manager:dictionary:value:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (31, 25, '新增字典值', 'A', null, null, '/manager/api/v1/dictionary_value', 'POST', null, 'manager:dictionary:value:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (32, 25, '修改字典值', 'A', null, null, '/manager/api/v1/dictionary_value', 'PUT', null, 'manager:dictionary:value:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (33, 25, '更新字典值目录状态', 'A', null, null, '/manager/api/v1/dictionary_value/status', 'PUT', null, 'manager:dictionary:value:status', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (34, 25, '删除字典值', 'A', null, null, '/manager/api/v1/dictionary_value', 'DELETE', null, 'manager:dictionary:value:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (35, 3, '菜单管理', 'M', 'ManagerMenu', 'menu', null, null, '/admin/manager/menu', null, '/admin/manager/menu/index', null, 0, 0, 1, 1, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (36, 35, '查询菜单', 'A', null, null, '/manager/api/v1/menus', 'GET', null, 'manager:menu:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (37, 35, '新增菜单', 'A', null, null, '/manager/api/v1/menu', 'POST', null, 'manager:menu:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (38, 35, '修改菜单', 'A', null, null, '/manager/api/v1/menu', 'PUT', null, 'manager:menu:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (39, 35, '删除菜单', 'A', null, null, '/manager/api/v1/menu', 'DELETE', null, 'manager:menu:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (40, 3, '部门管理', 'M', 'ManagerDepartment', 'user-group', null, null, '/admin/manager/department', null, '/admin/manager/department/index', null, 0, 0, 1, null, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (41, 40, '新增部门', 'A', null, null, '/manager/api/v1/department', 'POST', null, 'manager:department:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (42, 40, '修改部门', 'A', null, null, '/manager/api/v1/department', 'PUT', null, 'manager:department:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (43, 40, '删除部门', 'A', null, null, '/manager/api/v1/department', 'DELETE', null, 'manager:department:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (44, 3, '角色管理', 'M', 'ManagerRole', 'safe', null, null, '/admin/manager/role', null, '/admin/manager/role/index', null, 0, null, 0, null, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (45, 44, '新增角色', 'A', null, null, '/manager/api/v1/role', 'POST', null, 'manager:role:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (46, 44, '修改角色', 'A', null, null, '/manager/api/v1/role', 'PUT', null, 'manager:role:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (47, 44, '修改角色状态', 'A', null, null, '/manager/api/v1/role/status', 'PUT', null, 'manager:role:update:status', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (48, 44, '删除角色', 'A', null, null, '/manager/api/v1/role', 'DELETE', null, 'manager:role:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (49, 44, '角色菜单管理', 'G', null, null, null, null, null, 'manager:role:menu', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (50, 49, '查询角色菜单', 'A', null, null, '/manager/api/v1/role/menu_ids', 'GET', null, 'manager:role:menu:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (51, 49, '修改角色菜单', 'A', null, null, '/manager/api/v1/role/menu', 'POST', null, 'manager:role:menu:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (52, 3, '用户管理', 'M', 'ManagerUser', 'user', null, null, '/admin/manager/user', null, '/admin/manager/user/index', null, 0, null, 1, null, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (53, 52, '查询用户列表', 'A', null, null, '/manager/api/v1/users', 'GET', null, 'manager:user:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (54, 52, '新增用户', 'A', null, null, '/manager/api/v1/user', 'POST', null, 'manager:user:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (55, 52, '修改用户', 'A', null, null, '/manager/api/v1/user', 'PUT', null, 'manager:user:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (56, 52, '删除用户', 'A', null, null, '/manager/api/v1/user', 'DELETE', null, 'manager:user:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (57, 52, '修改用户状态', 'A', null, null, '/manager/api/v1/user/status', 'PUT', null, 'manager:user:status', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (58, 52, '重置账号密码', 'A', null, null, '/manager/api/v1/user/password/reset', 'POST', null, 'manager:user:reset:password', '', null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (59, 1, '资源中心', 'M', 'SystemPlatformResource', 'file', null, null, '/admin/resource', null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (60, 59, '文件管理', 'M', 'ResourceFile', 'file', null, null, '/admin/resource/file', null, '/admin/resource/file/index', null, 0, 0, 1, null, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (61, 60, '目录管理', 'G', null, null, null, null, null, 'resource:directory:group', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (62, 61, '查看目录', 'A', null, null, '/resource/api/v1/directories', 'GET', null, 'resource:directory:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (63, 61, '新增目录', 'A', null, null, '/resource/api/v1/directory', 'POST', null, 'resource:directory:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (64, 61, '修改目录', 'A', null, null, '/resource/api/v1/directory', 'PUT', null, 'resource:directory:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (65, 61, '删除目录', 'A', null, null, '/resource/api/v1/directory', 'DELETE', null, 'resource:directory:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (66, 60, '文件管理', 'G', null, null, null, null, null, 'resource:file:group', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (67, 66, '查看文件', 'A', null, null, '/resource/api/v1/files', 'GET', null, 'resource:file:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (68, 66, '修改文件', 'A', null, null, '/resource/api/v1/file', 'PUT', null, 'resource:file:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (69, 66, '删除文件', 'A', null, null, '/resource/api/v1/file', 'DELETE', null, 'resource:file:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (70, 59, '导出管理', 'M', 'ResourceExport', 'export', null, null, '/admin/resource/export', null, '/admin/resource/export/index', null, 0, 0, 1, null, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (71, 70, '查看导出', 'A', null, null, '/resource/api/v1/exports', 'GET', null, 'resource:export:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (72, 70, '新增导出', 'A', null, null, '/resource/api/v1/export', 'POST', null, 'resource:export:file', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (73, 70, '删除导出', 'A', null, null, '/resource/api/v1/export', 'DELETE', null, 'resource:export:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (74, 1, '配置中心', 'M', 'SystemPlatformConfigure', 'code-block', null, null, '/admin/configure', null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (75, 74, '环境管理', 'M', 'ConfigureEnv', 'common', null, null, '/admin/configure/env', null, '/admin/configure/env/index', null, 0, null, 1, null, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (76, 75, '查看环境', 'A', null, null, '/configure/api/v1/envs', 'GET', null, 'configure:env:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (77, 75, '设置环境资源权限', 'A', null, null, '/manager/api/v1/resource/cfg_env', 'PUT', null, 'configure:env:resource:permission', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (78, 75, '新增环境', 'A', null, null, '/configure/api/v1/env', 'POST', null, 'configure:env:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (79, 75, '修改环境', 'A', null, null, '/configure/api/v1/env', 'PUT', null, 'configure:env:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (80, 75, '修改环境状态', 'A', null, null, '/configure/api/v1/env/status', 'PUT', null, 'configure:env:update:status', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (81, 75, '删除环境', 'A', null, null, '/configure/api/v1/env', 'DELETE', null, 'configure:env:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (82, 75, '查看环境Token', 'A', null, null, '/configure/api/v1/env/token', 'GET', null, 'configure:env:token:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (83, 75, '重置环境token', 'A', null, null, '/configure/api/v1/env/token', 'PUT', null, 'configure:env:token:reset', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (84, 74, '服务管理', 'M', 'ConfigureServer', 'apps', null, null, '/admin/configure/server', null, '/admin/configure/server/index', null, 0, null, 1, null, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (85, 84, '查询服务', 'A', null, null, '/configure/api/v1/servers', 'GET', null, 'configure:server:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (86, 84, '设置服务资源权限', 'A', null, null, '/manager/api/v1/resource/cfg_server', 'PUT', null, 'configure:server:resource:permission', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (87, 84, '新增服务', 'A', null, null, '/configure/api/v1/server', 'POST', null, 'configure:server:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (88, 84, '修改服务', 'A', null, null, '/configure/api/v1/server', 'PUT', null, 'configure:server:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (89, 84, '修改服务状态', 'A', null, null, '/configure/api/v1/server/status', 'PUT', null, 'configure:server:update:status', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (90, 84, '删除服务', 'A', null, null, '/configure/api/v1/server', 'DELETE', null, 'configure:server:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (91, 74, '业务变量', 'M', 'ConfigureBusiness', 'code', null, null, '/admin/configure/business', null, '/admin/configure/business/index', null, 0, null, 1, null, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (92, 91, '查看业务变量', 'A', null, null, '/configure/api/v1/businesses', 'GET', null, 'configure:business:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (93, 91, '新增业务变量', 'A', null, null, '/configure/api/v1/business', 'POST', null, 'configure:business:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (94, 91, '修改业务变量', 'A', null, null, '/configure/api/v1/business', 'PUT', null, 'configure:business:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (95, 91, '删除业务变量', 'A', null, null, '/configure/api/v1/business', 'DELETE', null, 'configure:business:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (96, 91, '查看业务变量值', 'A', null, null, '/configure/business/values', 'get', null, 'configure:business:value:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (97, 91, '设置业务变量值', 'A', null, null, '/configure/business/values', 'PUT', null, 'configure:business:value:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (98, 74, '资源变量', 'M', 'ConfigureResource', 'unordered-list', null, null, '/admin/configure/resource', null, '/admin/configure/resource/index', null, 0, null, 1, null, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (99, 98, '查看资源', 'A', null, null, '/configure/api/v1/resources', 'GET', null, 'configure:resource:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (100, 98, '新增资源', 'A', null, null, '/configure/api/v1/resource', 'POST', null, 'configure:resource:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (101, 98, '修改资源', 'A', null, null, '/configure/api/v1/resource', 'PUT', null, 'configure:resource:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (102, 98, '删除资源', 'A', null, null, '/configure/api/v1/resource', 'DELETE', null, 'configure:resource:delete', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (103, 98, '查看业务变量值', 'A', null, null, '/configure/resource/values', 'get', null, 'configure:resource:value:query', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (104, 98, '设置业务变量值', 'A', null, null, '/configure/resource/values', 'PUT', null, 'configure:resource:value:update', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (105, 74, '配置模板', 'M', 'ConfgureTemplate', 'file', null, null, '/admin/configure/template', null, '/admin/configure/template/index', null, 0, null, 1, null, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (106, 105, '模板管理', 'G', null, null, null, null, null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (107, 106, '查看模板历史版本', 'A', null, null, '/configure/api/v1/templates', 'GET', null, 'configure:template:history', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (108, 106, '查看指定模板详细数据', 'A', null, null, '/configure/api/v1/template', 'GET', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (109, 106, '查看当前正在使用的模板', 'A', null, null, '/configure/api/v1/template/current', 'GET', null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (110, 106, '提交模板', 'A', null, null, '/configure/api/v1/template', 'POST', null, 'configure:template:add', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (111, 106, '模板对比', 'A', null, null, '/configure/api/v1/template/compare', 'POST', null, 'configure:template:compare', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (112, 106, '切换模板', 'A', null, null, '/configure/api/v1/template/switch', 'POST', null, 'configure:template:switch', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (113, 106, '模板预览', 'A', null, null, '/configure/api/v1/template/preview', 'POST', null, 'configure:template:preview', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (114, 105, '配置管理', 'G', null, null, null, null, null, null, null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (115, 114, '配置对比', 'A', null, null, '/configure/api/v1/configure/compare', 'POST', null, 'configure:configure:compare', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (116, 114, '同步配置', 'A', null, null, '/configure/api/v1/configure', 'PUT', null, 'configure:configure:sync', null, null, 0, null, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO `menu` (`id`, `parent_id`, `title`, `type`, `keyword`, `icon`, `api`, `method`, `path`, `permission`, `component`, `redirect`, `weight`, `is_hidden`, `is_cache`, `is_home`, `is_affix`, `created_at`, `updated_at`) VALUES (117, 0, '饥荒游戏平台', 'R', 'AppPlatform', 'apps', null, null, '/dst', null, 'Layout', null, 2, 0, null, null, null, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 5);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 5);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 5);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 6);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 6);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 6);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 7);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 7);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 7);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 8);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 8);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 8);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 9);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 9);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 9);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 10);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 10);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 10);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 11);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 11);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 11);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 12);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 12);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 12);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 13);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 13);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 13);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 14);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 14);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 14);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 15);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 15);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 15);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 16);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 16);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 16);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 17);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 17);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 17);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 18);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 18);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 18);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 19);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 19);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 19);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 20);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 20);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 20);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 21);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 21);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 21);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 22);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 22);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 22);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 23);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 23);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 23);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 24);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 24);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 4, 24);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 26);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 26);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 25, 26);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 27);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 27);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 25, 27);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 28);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 28);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 25, 28);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 29);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 29);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 25, 29);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 30);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 30);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 25, 30);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 31);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 31);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 25, 31);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 32);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 32);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 25, 32);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 33);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 33);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 25, 33);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 34);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 34);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 25, 34);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 36);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 36);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 35, 36);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 37);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 37);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 35, 37);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 38);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 38);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 35, 38);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 39);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 39);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 35, 39);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 41);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 41);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 40, 41);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 42);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 42);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 40, 42);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 43);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 43);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 40, 43);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 50);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 50);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 44, 50);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 49, 50);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 51);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 51);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 44, 51);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 49, 51);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 45);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 45);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 44, 45);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 46);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 46);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 44, 46);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 47);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 47);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 44, 47);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 48);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 48);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 44, 48);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 49);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 49);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 44, 49);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 53);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 53);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 52, 53);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 54);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 54);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 52, 54);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 55);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 55);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 52, 55);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 56);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 56);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 52, 56);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 57);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 57);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 52, 57);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 58);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 58);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 52, 58);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 4);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 4);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 25);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 25);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 35);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 35);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 40);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 40);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 44);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 44);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 52);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 3, 52);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 62);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 62);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 60, 62);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 61, 62);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 63);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 63);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 60, 63);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 61, 63);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 64);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 64);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 60, 64);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 61, 64);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 65);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 65);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 60, 65);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 61, 65);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 67);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 67);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 60, 67);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 66, 67);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 68);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 68);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 60, 68);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 66, 68);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 69);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 69);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 60, 69);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 66, 69);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 61);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 61);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 60, 61);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 66);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 66);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 60, 66);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 71);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 71);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 70, 71);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 72);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 72);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 70, 72);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 73);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 73);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 70, 73);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 60);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 60);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 70);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 59, 70);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 76);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 76);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 75, 76);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 77);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 77);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 75, 77);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 78);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 78);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 75, 78);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 79);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 79);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 75, 79);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 80);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 80);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 75, 80);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 81);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 81);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 75, 81);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 82);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 82);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 75, 82);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 83);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 83);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 75, 83);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 85);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 85);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 84, 85);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 86);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 86);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 84, 86);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 87);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 87);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 84, 87);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 88);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 88);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 84, 88);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 89);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 89);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 84, 89);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 90);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 90);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 84, 90);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 92);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 92);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 91, 92);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 93);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 93);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 91, 93);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 94);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 94);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 91, 94);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 95);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 95);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 91, 95);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 96);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 96);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 91, 96);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 97);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 97);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 91, 97);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 99);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 99);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 98, 99);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 100);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 100);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 98, 100);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 101);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 101);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 98, 101);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 102);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 102);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 98, 102);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 103);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 103);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 98, 103);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 104);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 104);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 98, 104);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 107);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 107);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 105, 107);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 106, 107);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 108);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 108);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 105, 108);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 106, 108);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 109);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 109);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 105, 109);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 106, 109);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 110);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 110);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 105, 110);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 106, 110);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 111);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 111);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 105, 111);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 106, 111);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 112);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 112);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 105, 112);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 106, 112);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 113);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 113);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 105, 113);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 106, 113);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 115);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 115);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 105, 115);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 114, 115);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 116);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 116);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 105, 116);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 114, 116);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 106);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 106);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 105, 106);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 114);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 114);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 105, 114);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 75);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 75);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 84);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 84);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 91);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 91);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 98);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 98);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 105);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 74, 105);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 2);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 3);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 59);
INSERT INTO `menu_closure` ( `parent`, `children`) VALUES ( 1, 74);

INSERT INTO `role` (`id`, `parent_id`, `name`, `keyword`, `status`, `description`, `department_ids`, `data_scope`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 0, '超级管理员', 'superAdmin', 1, '超级管理员  ', NULL, 'ALL', UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0);

INSERT INTO `user` (`id`, `department_id`, `role_id`, `name`, `nickname`, `gender`, `avatar`, `email`, `phone`, `password`, `status`, `setting`, `token`, `logged_at`, `created_at`, `updated_at`) VALUES (1, 1, 1, '超级管理员', '超级管理员', 'M', 'a9f224627346905e258d771e4043f921', 'admin@dstgo.cn', '123456789', '$2a$10$9qRJe9KQo6sEcU8ipKg.e.dkl2E7Wy64SigYlgraTAn.1paHFq6W.', 1, '{"theme":"light","themeColor":"#165DFF","skin":"default","tabBar":true,"menuWidth":200,"layout":"default","language":"zh_CN","animation":"gp-fade"}', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXBhcnRtZW50SWQiOjEsImRlcGFydG1lbnRLZXl3b3JkIjoiZHN0Z28iLCJleHAiOjE3NDE4ODA4MjYsImlhdCI6MTc0MTg3MzYyNSwibmJmIjoxNzQxODczNjI1LCJyb2xlSWQiOjEsInJvbGVLZXl3b3JkIjoic3VwZXJBZG1pbiIsInVzZXJJZCI6MX0.UQqKBGx_8suE4uudUWPXcioqZN0KwyQQi2eHtwJiGHA', UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

INSERT INTO `user_role` (`id`, `role_id`, `user_id`) VALUES (1, 1, 1);

SET FOREIGN_KEY_CHECKS = 1;