// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/246859/steamapi"
	"github.com/docker/docker/client"
	"github.com/dstgo/wilson/internal/conf"
	"github.com/dstgo/wilson/internal/data"
	"github.com/dstgo/wilson/internal/service/archive"
	"github.com/dstgo/wilson/internal/service/cronjob"
	"github.com/dstgo/wilson/internal/service/daemon"
	"github.com/dstgo/wilson/internal/service/mod"
	"github.com/dstgo/wilson/internal/service/player"
	"github.com/dstgo/wilson/internal/service/server"
	"github.com/dstgo/wilson/internal/service/setting"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func setupService(cfg *conf.WigfridConf, datasource *data.DataSource, dockerClient *client.Client, steamClient *steamapi.Client, logger log.Logger) RegisteredService {
	hostHandler := daemon.NewHostHandler(dockerClient, cfg)
	containerHandler := daemon.NewContainerHandler(dockerClient, datasource)
	service := daemon.NewService(hostHandler, containerHandler)
	serverService := server.NewService()
	playerService := player.NewService()
	settingService := setting.NewService()
	archiveService := archive.NewService()
	cronjobService := cronjob.NewService()
	modService := mod.NewService()
	registeredService := RegisteredService{
		daemon:  service,
		server:  serverService,
		player:  playerService,
		setting: settingService,
		archive: archiveService,
		cron:    cronjobService,
		mod:     modService,
	}
	return registeredService
}
