// Code generated by swaggo/swag at 2023-10-14 00:20:26.4191013 +0800 CST m=+3.789450401. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplateappapi = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "to test app api if is ok",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "app test ping api",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ping name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "request.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.RegisterRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoappapi holds exported Swagger Info so clients can modify it
var SwaggerInfoappapi = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Wilson App Internal API Documentation",
	Description:      "Wilson api documentation",
	InfoInstanceName: "appapi",
	SwaggerTemplate:  docTemplateappapi,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoappapi.InstanceName(), SwaggerInfoappapi)
}
