basePath: /api/v1
definitions:
  request.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  request.RegisterRequest:
    properties:
      code:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: Wilson api documentation
  title: Wilson App Internal API Documentation
  version: v1.0.0
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: to test app api if is ok
      parameters:
      - description: ping name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: app test ping api
      tags:
      - system
swagger: "2.0"
