# Data validation part
[validate]
isnil = "Must be empty"
isempty = "must be default"
required = "is a required value and cannot be empty"
empty = "cannot be zero value"
notnil = "cannot be empty"
oneof = "Must be one of [%v] several values"
notoneof = "Cannot be one of [%v] several values"
gt = "Must be greater than %v"
gte = "Must be greater than or equal to %v"
lt = "Must be less than %v"
lte = "Must be less than or equal to %v"
eq = "Must be equal to %v"
match = "Must match the regular expression %v"
multiple = "Must be a multiple of %v"
date = "must be a valid date format"

[validate. length]
range = "The length must be between %v and %v"
max = "The length must be less than or equal to %v"
min = "The length must be greater than or equal to %v"
eq = "The length must be equal to %v"

[validate. string]
email = "Must be a valid email format"
url = "must be a valid URL"
requrl = "Must be a valid request URL"
requri = "must be a valid request URI"
alpha = "Can only contain English letters"
digit = "can only contain numbers"
alphanum = "Can only contain English letters and numbers"
unicode = "can only contain unicode alphabetic characters"
unicodenum = "Can only contain unicode decimal numbers"
unicodeletternum = "Can only contain unicode letters and numbers"
unicodenumch = "Can only contain unicode numeric characters"
lower = "Must be a lowercase string"
upper = "Must be an uppercase string"
hex = "Must be a hexadecimal number"
hexcolor = "Must be a hexadecimal color"
rgb = "Must be RGB format color code"
int = "Must be an integer number"
float = "Must be a floating point number"
uuidv3 = "Must be a valid UUID v3"
uuidv4 = "Must be a valid UUID v4"
uuidv5 = "Must be a valid UUID v5"
uuid = "Must be a valid UUID"
creditcard = "Must be a valid credit card number"
isbn10 = "Must conform to the ISBN-10 specification"
isbn13 = "Must conform to the ISBN-13 specification"
isbn = "Must conform to the ISBN specification"
json = "Must conform to JSON format"
ascii = "can only contain ASCII characters"
printable = "can only contain printable characters"
multibyte = "Can only contain multibyte characters"
fullwidth = "Can only contain full-width characters"
halfwidth = "Can only contain half-width characters"
fullhalfwidth = "Can only contain full-width and half-width characters"
base64 = "Must be Base64 encoded"
base64uri = "Must be a base64 encoded data URI"
e164 = "Must be a valid E164 number"
2code = "Must be a valid two-letter country code"
3code = "Must be a three-letter country code"
iso4217code = "Must be a valid ISO4217 currency code"
dial = "must be a valid dial string"
mac = "Must be a valid MAC address"
ip = "must be a valid IP address"
ipv4 = "Must be a valid IPv4 address"
ipv6 = "Must be a valid IPv6 address"
subdomain = "must be a valid subdomain"
domain = "must be a valid domain name"
dns = "must be a valid DNS name"
host = "must be a valid hostname"
port = "must be a valid port"
mongoid = "Must be a valid hex-encoded MongoDB ObjectId"
latitude = "must be a valid latitude"
longitude = "Must be a valid longitude"
ssn = "Must be a valid SSN code"
version = "must be a valid semantic version"

# Some commonly used field names
[field]
name = "Name"
email = "email"
username = "username"
password = "password"
phone = "Mobile phone number"
age = "age"
userid = "User ID"

# error message section
[http]
404 = "The requested resource does not exist"
405 = "Unsupported HTTP Method"
500 = "Internal server error"

[jwt]
parsedFailed = "User authentication failed, please try to log in again"
expired = "User credentials expired, please log in again"