// Package swagger Code generated by swaggo/swag at 2023-10-16 16:22:58.2778803 +0800 CST m=+3.452374101. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplateappapi = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://mit-license.org/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/forgotpwd": {
            "post": {
                "description": "forgot password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "ForgotPasswd",
                "parameters": [
                    {
                        "description": "comment",
                        "name": "changePasswdBoy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/login": {
            "post": {
                "description": "if login success, return jwt token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "comment",
                        "name": "loginBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginOption"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/logout": {
            "delete": {
                "description": "user logout",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {}
            }
        },
        "/auth/register": {
            "post": {
                "description": "user register api",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "comment",
                        "name": "registerBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/email/code": {
            "get": {
                "description": "auth code email api",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "SendCodeEmail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/ping": {
            "get": {
                "description": "to test app api if is ok",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Ping",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ping name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/role/create": {
            "post": {
                "description": "create a new role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "NewRole",
                "responses": {}
            }
        },
        "/role/grant": {
            "post": {
                "description": "grant permissions for the specified role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "GrantPermForRole",
                "responses": {}
            }
        },
        "/role/perm/create": {
            "post": {
                "description": "create a new permission",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "NewPermission",
                "responses": {}
            }
        },
        "/role/perm/remove": {
            "delete": {
                "description": "remove the specified permission",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "RemovePermission",
                "responses": {}
            }
        },
        "/role/perm/update": {
            "post": {
                "description": "update the specified permission info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "UpdatePermission",
                "responses": {}
            }
        },
        "/role/remove": {
            "delete": {
                "description": "remove a role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "RemoveRole",
                "responses": {}
            }
        },
        "/role/update": {
            "post": {
                "description": "update the specified role info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "UpdateRole",
                "responses": {}
            }
        },
        "/user/info": {
            "get": {
                "description": "get specific user simple info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "GetUserInfo",
                "responses": {}
            }
        },
        "/user/list": {
            "get": {
                "description": "get specific user list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "GetUserInfoList",
                "responses": {}
            }
        },
        "/user/remove": {
            "get": {
                "description": "Remove the specific user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "RemoveUser",
                "responses": {}
            }
        },
        "/user/update": {
            "get": {
                "description": "update the specific user info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "UpdateUserInfo",
                "responses": {}
            }
        }
    },
    "definitions": {
        "request.ForgotPasswordRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "auth code get from user binding email",
                    "type": "string",
                    "example": "F294484D"
                },
                "password": {
                    "description": "length of the password must be in range [10,30]",
                    "type": "string",
                    "example": "123456789"
                }
            }
        },
        "request.LoginOption": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "length of the password must be in range [10,30]",
                    "type": "string",
                    "example": "123456789"
                },
                "username": {
                    "description": "length of the username must be in range [6,20], and username must be Alphanumeric",
                    "type": "string",
                    "example": "123456@example.com/username"
                }
            }
        },
        "request.RegisterRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "8-digit auth code get from user binding email, and it must be Alphanumeric",
                    "type": "string",
                    "example": "F294484D"
                },
                "password": {
                    "description": "length of the password must be in range [10,30]",
                    "type": "string",
                    "example": "123456789"
                },
                "username": {
                    "description": "length of the username must be in range [6,20], and username must be Alphanumeric",
                    "type": "string",
                    "example": "123456@example.com/username"
                }
            }
        }
    }
}`

// SwaggerInfoappapi holds exported Swagger Info so clients can modify it
var SwaggerInfoappapi = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Wilson App Internal API Documentation",
	Description:      "Wilson api documentation",
	InfoInstanceName: "appapi",
	SwaggerTemplate:  docTemplateappapi,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoappapi.InstanceName(), SwaggerInfoappapi)
}
