// Package swagger Code generated by swaggo/swag at 2023-10-17 12:56:21.6804682 +0800 CST m=+2.779276701. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplateappapi = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://mit-license.org/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/forgotpwd": {
            "post": {
                "description": "forgot password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "ForgotPassword",
                "parameters": [
                    {
                        "description": "Account ID",
                        "name": "form",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ForgotPasswordOption"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "if login success, return jwt token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "comment",
                        "name": "loginBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginOption"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.Token"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "user logout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "user register api",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "comment",
                        "name": "registerBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterOption"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/email/code": {
            "get": {
                "description": "auth code email api",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "SendCodeEmail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "test app api if is ok",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Ping",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ping name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.PingReply"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/role/create": {
            "post": {
                "description": "create a new role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "NewRole",
                "responses": {}
            }
        },
        "/role/grant": {
            "post": {
                "description": "grant permissions for the specified role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "GrantPermForRole",
                "responses": {}
            }
        },
        "/role/perm/create": {
            "post": {
                "description": "create a new permission",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "NewPermission",
                "responses": {}
            }
        },
        "/role/perm/remove": {
            "delete": {
                "description": "remove the specified permission",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "RemovePermission",
                "responses": {}
            }
        },
        "/role/perm/update": {
            "post": {
                "description": "update the specified permission info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "UpdatePermission",
                "responses": {}
            }
        },
        "/role/remove": {
            "delete": {
                "description": "remove a role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "RemoveRole",
                "responses": {}
            }
        },
        "/role/update": {
            "post": {
                "description": "update the specified role info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "UpdateRole",
                "responses": {}
            }
        },
        "/user/info": {
            "get": {
                "description": "get specific user simple info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "GetUserInfo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user.Info"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/list": {
            "get": {
                "description": "get specific user list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "GetUserInfoList",
                "parameters": [
                    {
                        "description": "comment",
                        "name": "userPageOptIon",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.PageOption"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/user.Info"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/remove": {
            "delete": {
                "description": "Remove the specific user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "RemoveUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "userId",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/user/update": {
            "post": {
                "description": "update the specific user info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "UpdateUserInfo",
                "parameters": [
                    {
                        "description": "comment",
                        "name": "updateInfoOption",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateInfoOption"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 2000
                },
                "data": {},
                "err": {
                    "type": "string"
                },
                "msg": {
                    "type": "string",
                    "example": "operation success"
                }
            }
        },
        "auth.ForgotPasswordOption": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "auth code get from user binding email",
                    "type": "string",
                    "example": "F294484D"
                },
                "password": {
                    "description": "length of the password must be in range [10,30]",
                    "type": "string",
                    "example": "123456789"
                }
            }
        },
        "auth.LoginOption": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "length of the password must be in range [10,30]",
                    "type": "string",
                    "example": "123456789"
                },
                "username": {
                    "description": "length of the username must be in range [6,20], and username must be Alphanumeric",
                    "type": "string",
                    "example": "123456@example.com/username"
                }
            }
        },
        "auth.PingReply": {
            "type": "object",
            "properties": {
                "reply": {
                    "type": "string",
                    "example": "hello wendy! Now is 2023-10-17 11:07:21.696 +08:00."
                }
            }
        },
        "auth.RegisterOption": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "8-digit auth code get from user binding email, and it must be Alphanumeric",
                    "type": "string",
                    "example": "F294484D"
                },
                "password": {
                    "description": "length of the password must be in range [10,30]",
                    "type": "string",
                    "example": "123456789"
                },
                "username": {
                    "description": "length of the username must be in range [6,20], and username must be Alphanumeric",
                    "type": "string",
                    "example": "123456@example.com/username"
                }
            }
        },
        "auth.Token": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6InN0cmFuZ2VyIiwidXNlcklkIjoiMDA1YjQzOTctOTRjMi00YWZjLWIzNTEtNWIzY2VkNzI4MDkzIiwiaXNzIjoid2lsc29uIiwiZXhwIjoxNjk3MzI0ODY4LCJpYXQiOjE2OTcyODg4NjgsImp0aSI6IjdkZDI4NDZlLTFkZjEtNDBkMS04YmZlLTA3ZGI3ZmE4NmFhYiJ9.HnAaz-WOmugqfdz_oXphsJY_zQl3FCzrtYCm90WJgGU"
                }
            }
        },
        "user.Info": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2022-01-01 00:00:00"
                },
                "email": {
                    "type": "string",
                    "example": "jacklove@lol.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "jack"
                },
                "uuid": {
                    "type": "string",
                    "example": "55BBA4ED-18D3-790F-EABF-A5330E527586"
                }
            }
        },
        "user.PageOption": {
            "type": "object",
            "properties": {
                "desc": {
                    "description": "if is reverse order",
                    "type": "boolean",
                    "example": true
                },
                "order": {
                    "description": "specified field",
                    "type": "string",
                    "example": "email"
                },
                "page": {
                    "description": "page",
                    "type": "integer",
                    "example": 1
                },
                "search": {
                    "description": "search text, should be of one username or email",
                    "type": "string",
                    "example": "jacklove"
                },
                "size": {
                    "description": "size of page",
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "user.UpdateInfoOption": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "new email",
                    "type": "string",
                    "example": "jack@google.com"
                },
                "id": {
                    "description": "specified user id",
                    "type": "integer",
                    "example": 1
                },
                "password": {
                    "description": "new password",
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "description": "new username",
                    "type": "string",
                    "example": "jack"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfoappapi holds exported Swagger Info so clients can modify it
var SwaggerInfoappapi = &swag.Spec{
	Version:          "v1.0.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Wilson App Internal API Documentation",
	Description:      "Wilson api documentation",
	InfoInstanceName: "appapi",
	SwaggerTemplate:  docTemplateappapi,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoappapi.InstanceName(), SwaggerInfoappapi)
}
