basePath: /open/doc/
definitions:
  request.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  request.RegisterRequest:
    properties:
      code:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: Wilson api documentation
  title: Wilson App Internal API Documentation
  version: v1.0.0
paths:
  /open/user/info:
    get:
      consumes:
      - application/json
      description: get user simple info
      parameters:
      - description: comment
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: path params example
      tags:
      - ""
swagger: "2.0"
