// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package openapi

import (
	"github.com/dstgo/wilson/app/api/openapi/user"
	"github.com/dstgo/wilson/app/conf"
	"github.com/dstgo/wilson/app/dao/userDao"
	"github.com/dstgo/wilson/app/data"
	"github.com/dstgo/wilson/app/logic/userLogic"
	"github.com/dstgo/wilson/pkg/route"
)

// Injectors from wire.go:

//go:generate wire gen
func NewApiRouter(appConf *conf.AppConf, rootRouter *route.Router, datasource *data.DataSource) ApiRouter {
	userInfoDao := userDao.NewUserInfoDao(datasource)
	userInfoLogic := userLogic.NewUserLogic(userInfoDao)
	userInfoApi := user.NewUserInfoApi(userInfoLogic)
	userRouter := user.NewUserRouter(rootRouter, userInfoApi)
	apiRouter := ApiRouter{
		UserApi: userRouter,
	}
	return apiRouter
}
