name: DST Server Docker Build and Push

permissions:
  contents: read

on:
  schedule:
    - cron: '0 2 * * *' # run every-day at 2am
  workflow_dispatch: # allow to run manually

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: dstgo/dst-server
  DOCKERFILE_PATH: deploy/dontstarve/docker/Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:temp

      - name: Get DST server version from image
        id: get_version
        run: |
          VERSION=$(docker run --rm --entrypoint /bin/bash ${{env.IMAGE_NAME}} -c 'cat $DST_VERSION_FILE')
          echo "DST_VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "DST_VERSION=${VERSION}"

      - name: Tag Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:temp ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker tag ${{ env.IMAGE_NAME }}:temp ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.DST_VERSION }}
          echo "Tagged images:"
          docker images | grep ${{ env.IMAGE_NAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.DST_VERSION }}
          echo "Pushed images:"
          echo "${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          echo "${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.DST_VERSION }}"